"""initial tables

Revision ID: acf140e00328
Revises: 
Create Date: 2026-03-10 15:15:26.604922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'acf140e00328'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('hashed_password', sa.Text(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('organization', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table('submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'DOCUMENTS_UPLOADED', 'ANALYZING', 'AWAITING_CHAT', 'SCORING', 'COMPLETED', 'FAILED', name='submissionstatus'), nullable=False),
    sa.Column('extracted_features', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submissions_user_id'), 'submissions', ['user_id'], unique=False)
    op.create_table('conversation_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('target_feature', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_messages_submission_id'), 'conversation_messages', ['submission_id'], unique=False)
    op.create_table('credit_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('risk_tier', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='risktier'), nullable=False),
    sa.Column('ml_probability', sa.Float(), nullable=True),
    sa.Column('score_breakdown', sa.Text(), nullable=True),
    sa.Column('positive_signals', sa.Text(), nullable=True),
    sa.Column('improvement_areas', sa.Text(), nullable=True),
    sa.Column('report_text', sa.Text(), nullable=True),
    sa.Column('data_sources', sa.Text(), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('is_shared_with_lender', sa.Boolean(), nullable=False),
    sa.Column('lender_decision', sa.Enum('APPROVED', 'DECLINED', 'MANUAL_REVIEW', name='lenderdecision'), nullable=True),
    sa.Column('lender_notes', sa.Text(), nullable=True),
    sa.Column('decision_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_reports_submission_id'), 'credit_reports', ['submission_id'], unique=True)
    op.create_index(op.f('ix_credit_reports_user_id'), 'credit_reports', ['user_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('doc_type', sa.String(length=100), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('extraction_confidence', sa.Float(), nullable=True),
    sa.Column('is_low_confidence', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_submission_id'), 'documents', ['submission_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_submission_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_credit_reports_user_id'), table_name='credit_reports')
    op.drop_index(op.f('ix_credit_reports_submission_id'), table_name='credit_reports')
    op.drop_table('credit_reports')
    op.drop_index(op.f('ix_conversation_messages_submission_id'), table_name='conversation_messages')
    op.drop_table('conversation_messages')
    op.drop_index(op.f('ix_submissions_user_id'), table_name='submissions')
    op.drop_table('submissions')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
